# Site settings
title: Hack A Minute.
email: abhijithoskeri@gmail.com
description: >
    Lets take things apart and look.
baseurl: ""
url: "http://hoskeri.net"
github_username:  hoskeri

# Build settings
markdown: kramdown
